
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150226 (SVN rev 63)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SUBSTRING = 9;
  public static final int O_BOX = 21;
  public static final int STRING_LITERAL = 40;
  public static final int MULT = 28;
  public static final int C_PAREN = 18;
  public static final int LENGTHOFSTRING = 12;
  public static final int O_PAREN = 17;
  public static final int DOUBLE = 13;
  public static final int GREATER = 32;
  public static final int LENGTHOFARRAY = 11;
  public static final int LESS = 31;
  public static final int MINUS = 27;
  public static final int SCAN = 8;
  public static final int BOOLEAN_LITERAL = 42;
  public static final int NOT = 39;
  public static final int AND = 37;
  public static final int SEMICOLON = 24;
  public static final int C_BOX = 22;
  public static final int OR = 38;
  public static final int COMMA = 23;
  public static final int DIV = 30;
  public static final int PLUS = 26;
  public static final int NULL_LITERAL = 43;
  public static final int IF = 3;
  public static final int EOF = 0;
  public static final int BOOLEAN = 14;
  public static final int ARREGLO = 16;
  public static final int RETURN = 6;
  public static final int C_CURLY = 20;
  public static final int O_CURLY = 19;
  public static final int error = 1;
  public static final int MOD = 29;
  public static final int EQ = 25;
  public static final int ELSE = 4;
  public static final int NOT_EQ = 36;
  public static final int WHILE = 2;
  public static final int LESS_EQ = 33;
  public static final int STRING = 15;
  public static final int STRINGTODOUBLE = 10;
  public static final int DOUBLE_LITERAL = 41;
  public static final int STRUCT = 5;
  public static final int PRINT = 7;
  public static final int IDENTIFIER = 44;
  public static final int EQ_EQ = 35;
  public static final int GREATER_EQ = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "WHILE",
  "IF",
  "ELSE",
  "STRUCT",
  "RETURN",
  "PRINT",
  "SCAN",
  "SUBSTRING",
  "STRINGTODOUBLE",
  "LENGTHOFARRAY",
  "LENGTHOFSTRING",
  "DOUBLE",
  "BOOLEAN",
  "STRING",
  "ARREGLO",
  "O_PAREN",
  "C_PAREN",
  "O_CURLY",
  "C_CURLY",
  "O_BOX",
  "C_BOX",
  "COMMA",
  "SEMICOLON",
  "EQ",
  "PLUS",
  "MINUS",
  "MULT",
  "MOD",
  "DIV",
  "LESS",
  "GREATER",
  "LESS_EQ",
  "GREATER_EQ",
  "EQ_EQ",
  "NOT_EQ",
  "AND",
  "OR",
  "NOT",
  "STRING_LITERAL",
  "DOUBLE_LITERAL",
  "BOOLEAN_LITERAL",
  "NULL_LITERAL",
  "IDENTIFIER"
  };

  /* non terminals */
  static final int tipo = 5;
  static final int l_statements = 1;
  static final int s = 0;
  static final int atomicExpression = 4;
  static final int statement = 2;
  static final int expression = 3;
}

